[providers]
php = "8.1"

[phases.setup]
nixPkgs = ["...", "php81", "php81Extensions.pdo", "php81Extensions.pgsql"]

[phases.build]
cmds = [
  "mkdir -p uploads logs",
  "chmod 755 uploads logs"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
